### ISSUE TITLE
Retail version?

### ISSUE THREAD

**Issue by scalp42** [Masquue/TinyInspect-FixBackdrop#1]
Hey @Masquue 

Any chance you could bring the fix to the retail version?

Thanks in advance

**Comment by Masquue** [comment]
@scalp42 Sorry, I don't play retail and haven't used TinyInspect of that version...

But the idea is simple if you want to fix yourself: 

Find every place `SetBackdrop` is called, then find the place where the frame, on which the `SetBackdrop` is called, is created using `CreateFrame`. Then add a fourth parameter `BackdropTemplateMixin and "BackdropTemplate"` in `CreateFrame`; and if there's already a fourth parameter, change it to `BackdropTemplateMixin and "BackdropTemplate,{original-text-in-fourth-string-parameter}"`.
